---
title: "U.S. Dams"
author: "Stephen Kaluzny"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("ggplot2")
library("dplyr")
library("leaflet")
```

## Get the Data
Use the `dams` package from CRAN to download all the NID data.
```{r getdata}
if(file.exists("dams_all.rds")) {
  dams_all <- readRDS("dams_all.rds")
} else {
  library("dams")
  dams_all <- get_nid()
  saveRDS(dams_all, file="dams_all.rds")
}
dim(dams_all)
names(dams_all)
```

```{r lower48}
dams_all <- dams_all %>%
  filter(State != "GU", State != "PR", State != "AK", State != "HI")
```

## Initial View of the Data
```{r explore01}
summary(dams_all)
```

## Missing Values
```{r missing}
missingCount <- sapply(dams_all, function(x) sum(is.na(x)))
missingCount <- missingCount[missingCount > 0]
o <- order(missingCount)
missingCount <- missingCount[o]
missingPercent <- missingCount/nrow(dams_all) * 100
data.frame(Variable = factor(names(missingCount), levels=names(missingCount)),
    PercentMissing = missingPercent) %>%
    ggplot(aes(Variable, PercentMissing)) + geom_bar(stat = "identity") +
	     coord_flip()
```

### Types of Dams
```{r}
with(dams_all, table(Dam_Type))
with(dams_all, table(Core))
with(dams_all, table(Foundation))
```

### Dam Locations
```{r eval=TRUE}
dams_all %>%
    leaflet() %>%
    addTiles() %>%
    addCircles(weight = 1, radius = dams_all$Dam_Height)
```

### Dam Area
Folsom dam is clearly an outlier.
Data says length is 102000 but Wikipedia has the overall length at 26730.
```{r area}
dams_all <- dams_all %>%
  mutate(Dam_Area = Dam_Length * Dam_Height)
ggplot(dams_all, aes(x=Dam_Area)) + geom_histogram()
```

### Rivers
```{r rivers}
sort(with(dams_all, 
    table(River)), decreasing = TRUE)[1:100]
```

### Big Dams
```{r big}
dams_all %>%
  filter(Dam_Height > 100) %>%
  # ggplot(aes(x=Dam_Height)) + geom_histogram()
  dim()
```